# Generated by Django 4.0.6 on 2022-08-03 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL)),
                ('team_memebers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('task_no', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=800)),
                ('sprint', models.IntegerField()),
                ('type_of_task', models.CharField(choices=[('bug', 'BUG'), ('task', 'task')], default='task', max_length=4)),
                ('status', models.CharField(choices=[('todo', 'TODO'), ('in_progress', 'IN_PROGRESS'), ('qc', 'QC'), ('uat', 'UAT'), ('ready_for_demo', 'READY_FOR_DEMO'), ('ready_for_prod_release', 'READY_FOR_PROD_RELEASE'), ('done', 'DONE'), ('cancelled', 'CANCELLED')], default='todo', max_length=22)),
                ('priority', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], default='medium', max_length=6)),
                ('original_estimate', models.TimeField()),
                ('time_logging', models.TimeField()),
                ('started_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.team')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
