# Generated by Django 4.0.6 on 2022-08-04 05:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 47, 53, 558770, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 47, 53, 558809, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(limit_choices_to={'groups__name__in': ['TeamMember', 'TeamLeader']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 47, 53, 558197, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 47, 53, 558235, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='original_estimate',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_logging',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_of_task',
            field=models.CharField(choices=[('bug', 'BUG'), ('task', 'TASK')], default='task', max_length=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 47, 53, 556461, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 47, 53, 557057, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'TeamLeader'}, on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_memebers',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'TeamMember'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
