# Generated by Django 4.0.6 on 2022-08-04 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_comment_created_at_alter_comment_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 49, 29, 752396, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 49, 29, 752435, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 49, 29, 751826, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 49, 29, 751864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='original_estimate',
            field=models.TimeField(default='04:23:46'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 49, 29, 750245, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 49, 29, 750790, tzinfo=utc)),
        ),
    ]
