# Generated by Django 4.0.6 on 2022-08-04 05:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_comment_created_at_alter_comment_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='original_estimate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_logging',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 51, 22, 296290, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 51, 22, 296346, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 51, 22, 295511, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 51, 22, 295552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 51, 22, 293914, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 5, 51, 22, 294497, tzinfo=utc)),
        ),
    ]
