# Generated by Django 4.0.6 on 2022-08-04 06:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_remove_task_original_estimate_remove_task_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 5, 20, 668599, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 5, 20, 668638, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 5, 20, 668029, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 5, 20, 668068, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 5, 20, 666436, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 5, 20, 667021, tzinfo=utc)),
        ),
    ]
