# Generated by Django 4.0.6 on 2022-08-04 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_created_by_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 6, 15, 591343, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 6, 15, 591382, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 6, 15, 590759, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 6, 15, 590798, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 6, 15, 589141, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 6, 6, 15, 589722, tzinfo=utc)),
        ),
    ]
